name: Selenium E2E Test         # GitHub Actions上で見える名前

on:                             # 何をきっかけにworkflowを動かすか
  push:                         # GitHubへpushされたタイミングで実行

jobs:                           # workflowの中で実行する作業のまとまり
  selenium-test:                # jobにつけた名前
    runs-on: ubuntu-latest      # GitHub側でUbuntuの実行環境を用意する

    steps:
        # GitHub上のコードを実行環境へ取得
        - name: Checkout repository
          uses: actions/checkout@v4

        # Node.jsを準備
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: "24"

        # 必要なライブラリをインストール
        - name: Install dependencies
          run: npm ci
          working-directory: 05_テスト自動化/Selenium-EC-site

        # ECサイトを起動
        - name: Start EC site
          run: python3 -m http.server 5500 --directory site &
          working-directory: 05_テスト自動化/Selenium-EC-site

        # Seleniumテストを実行
        - name: Run Selenium tests
          run: npm test
          working-directory: 05_テスト自動化/Selenium-EC-site

        # FAIL時のエビデンスをArtifactとして保存
        - name: Upload test evidence
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: selenium-test-evidence
            path: 05_テスト自動化/Selenium-EC-site/selenium-results/